### ISSUE TITLE
AttributeError: '_Environ' object has no attribute 'has_key'

### ISSUE THREAD

**Issue by nitrotm** [fedragon/scafor#3]
The error is triggered at this line of code introduced in last commit:

```
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 1072, in run_
    return self.run(edit)
  File "~/.config/sublime-text-3/Installed Packages/Scalafmt.sublime-package/Scalafmt.py", line 27, in run
```

I think the check should be:

```
if 'TERM' not in os.environ:
  ...
```

**Comment by fedragon** [comment]
@nitrotm Thanks, I have just pushed a new version with your suggested correction
